Upgrade to PostGIS 2.4.8/GEOS 3.6.4  to fix auto-analyze errors (#166)
PostGIS was updated from the custom built 2.4.0dev ff0a844e606622f45841fc25221bbaa136ed1001 to the production 2.4.8.  This means that  `ST_AsMVT()` arguments are now in sync with the documentation and all subsequent versions, rather than having a non-published order.  The tool's mvt usage has already been adjusted to check version string.

Here are errors I got with the current "openmaptiles/postgis" image (based on PostgreSQL 9.6.16) after running an openmaptiles import and generating vector tiles
```
ERROR:  relation "spatial_ref_sys" does not exist at character 23
QUERY:  SELECT proj4text FROM spatial_ref_sys WHERE srid = 3857 LIMIT 1
CONTEXT:  automatic analyze of table "gis.public.osm_waterway_linestring_gen2"
ERROR:  relation "spatial_ref_sys" does not exist at character 23
QUERY:  SELECT proj4text FROM spatial_ref_sys WHERE srid = 3857 LIMIT 1
CONTEXT:  automatic analyze of table "gis.public.osm_city_point"
ERROR:  relation "spatial_ref_sys" does not exist at character 23
QUERY:  SELECT proj4text FROM spatial_ref_sys WHERE srid = 3857 LIMIT 1
CONTEXT:  automatic analyze of table "gis.public.osm_poi_point"
...
```

After investigation, it seems this is due to [a change introduced in PostgreSQL 9.6.8](https://www.postgresql.org/docs/9.6/release-9-6-8.html), where the tighter "search_path" used by autovacuum workers may result in errors.

And that was fixed in PostGIS 2.4.3 by https://github.com/postgis/postgis/commit/40ac54854a82e4cbf554c9cef6bac5e32f575f21

Hence, the recommendation to use the latest versions for PostGIS 2.4 and GEOS 3.6.