Fix regression in tm2source key_field_as_attribute (#162)
When key_field is '', key_field_as_attribute should be set to ''
Otherwise Mapnik causes an error:
  column number 4 is out of range 0..3
  Error: basic_string::_S_construct null not valid